- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: This command will change the working directory
  shell:
    cmd: docker-compose up -d
    chdir: ../
